### ISSUE TITLE
Request to non-existing IP ignores Timeout

### ISSUE THREAD

**Issue by blacktea** [skellock/apisauce#102]
If I make a request to non-existing IP Apisauce ignores timeout and waits 63327...

Configuration:

```
  const api = apisauce.create({
    baseURL,
    headers: {
      'Cache-Control': 'no-cache'
    },
    timeout: 5000
  })
```

Result:

```
duration:63327
problem:NETWORK_ERROR
ok:false
status:null
headers:null
▶config:{}
adapter:~~~ xhrAdapter() ~~~
▶transformRequest:{}
▶transformResponse:{}
timeout:5000
xsrfCookieName:XSRF-TOKEN
xsrfHeaderName:X-XSRF-TOKEN
maxContentLength:-1
validateStatus:~~~ validateStatus() ~~~
▶headers:{}
baseURL:http://10.0.2.2/
method:get
url:http://10.0.2.2/users
▶params:{}
data:~~~ undefined ~~~
data:null
```

**Comment by skellock** [comment]
Sorry, I missed this.  Looks like you might be using React Native Android?

https://github.com/facebook/react-native/issues/11666 seems to indicate there's some problems with a fix incoming.

Outlined in that issue is a workaround using cancel tokens.

Are you able to reproduce the same issue with Fetch?  If I'm reading that right, it might be a problem with that as well since it's at the XMLHTTPRequest level.

Feel free to re-open if you reckon it's something I can fix.
