### ISSUE TITLE
camelize keys

### ISSUE THREAD

**Issue by mmahalwy** [skellock/apisauce#42]
Cannot do this in a transform:
```
response.data = camelizeKeys(response.data);
```

**Comment by mmahalwy** [comment]
The way I am getting around this is:
```
api.addResponseTransform(response => {
    if (response.data) {
      const data = camelizeKeys(response.data);

      Object.keys(response.data).forEach(key => {
        delete response.data[key];
      });

      Object.keys(data).forEach(key => response.data[key] = data[key]);
    }
  });
```

It's not elegant at all. Seems like I cannot change `response.data` by assigning a new object. I can only change keys and values.

**Comment by skellock** [comment]
Agreed. I really didn't like how I implemented that at all.

The problem is I wanted to [play it safe](https://github.com/skellock/apisauce/blob/master/lib/apisauce.js#L158) by passing a new object to each transform.  I was encountering situations where I was able to break things if i mutable the wrong object (like the `config`) object.

So although, it **looks** like the transform is receiving the response.  It's not.  It's receiving a decoy.

That's why changing references is messing up your evening.

I started out the immutable route, but after seeing how slow transforms were once you started passing large data (like file uploads), i opted for the solution you see now.

**Comment by mmahalwy** [comment]
@skellock makes sense. What do you suggest is the best way then? My solution works for now, but it's... not great.

**Comment by skellock** [comment]
Ok @mmahalwy , `apisauce@0.7.0` is now out.   Reassigning data (and everything else)  is now a thing.

```js
response.data = camelizeKeys(response.data)
```

**Comment by mmahalwy** [comment]
woohooo! Thank you!
