### ISSUE TITLE
Timeout not being detected

### ISSUE THREAD

**Issue by semiautomatix** [skellock/apisauce#61]
Good day, 

I'm not getting a timeout on an IP address that does not exist. Rather the app is waiting for a NETWORK_ERROR which can take a lot longer (several minutes in some circumstances). My setup below:

```
    const api = apisauce.create({
        // base URL is read from the "constructor"
        baseURL,
        // here are some default headers
        headers: {
            'Cache-Control': 'no-cache'
        },
        // 10 second timeout...
        timeout: 2000
    })
```

` const testURL = () => api.get('/');`

`const result = yield call(api.testURL);`

OR

```
api.testURL().then(
    (result) => console.warn(result),
    (err) => console.error(err)
  )

```
Regards

**Comment by semiautomatix** [comment]
Might be an Axios issue: https://github.com/mzabriskie/axios/issues/56

**Comment by skellock** [comment]
What is your environment? React Native? Version? Simulator? OS Version?

I've seen this behaviour on older versions of iOS 8 before.

**Comment by semiautomatix** [comment]
@skellock thanks for the reply, running Genymotion with Android 5.1.0

Ok, I've tried it out on Android 6.0.1 on an actual device and am receiving a NETWORK_ERROR, after several seconds, even though the timeout is set to 1 second.

**Comment by skellock** [comment]
There's a lot of layers in between your app & the call to the server.

Your App >  Apisauce > Axios > XMLHttpRequest JS > React Native Networking Bridge > JavaScriptCore > OkHttp or NSURLSession (depending on platform).  I've also seen the simulator and device perform differently too.

Having the right errors bubble up has been challenging.  See https://github.com/skellock/apisauce/issues/7 for a little more details why.

One thing I had considered before is that we might be able to set our own timeouts via a promise race.   You can do this now because Axios recently exposed a cancellation token.

Let me know if you have luck with that route.
